sudo: false
language: node_js
node_js:
  - 'stable'
env:
  - CXX=g++
addons:
  apt:
    packages:
    - gcc
    - g++
    - clang
script:
  - npm run prepublish
cache:
  directories:
    - node_modules
